### ISSUE TITLE
Final Result

### ISSUE THREAD

**Issue by mady143** [obeshor/Plant-Diseases-Detector#6]
Hi @obeshor ,

I had successfully implemented the tflite package in flutter but at last we are getting the output in that we are getting like {{confidence:0.78326,index:1,label:name}} i want to display the only label with specific font and style can you explain how can i get that

Thanks and Regards,
Manikantha Sekhar.

**Comment by obeshor** [comment]
Hey @mady143 

For Kotlin code,  check this [https://github.com/obeshor/Plant-Diseases-Detector/blob/master/GreenDoctor/app/src/main/java/isomora/com/greendoctor/Classifier.kt](url).
